set nocompatible

filetype plugin indent on
syntax enable

set background=dark
let g:solarized_termcolors=256
colorscheme solarized

set wrap
set textwidth=128
set formatoptions=tcqrn1
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set noshiftround

set ruler
set number
set visualbell
set encoding=utf-8
