set nocompatible

filetype plugin indent on
syntax on

set wrap
set textwidth=79
set formatoptions=tcqrn1
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set noshiftround

set ruler
set visualbell
set encoding=utf-8
